--Q1
DESC STUDENT;
--Q3
SELECT * 
FROM STUDENT;
--Q5
SELECT STU_NO, STU_NAME 
FROM STUDENT;
--Q7
SELECT STU_NO, STU_NAME, STU_GENDER
FROM STUDENT;
--Q9
SELECT STU_NO, STU_NAME, STU_GRADE, STU_CLASS
FROM STUDENT;
--Q11
SELECT *
FROM ENROL;
--Q13
SELECT DISTINCT(STU_DEPT)
FROM STUDENT;
--Q15
SELECT DISTINCT(STU_GRADE)
FROM STUDENT;
--Q17
SELECT DISTINCT STU_DEPT, STU_GRADE
FROM STUDENT;
--Q19
SELECT STU_WEIGHT - 5
FROM STUDENT;
--Q21
SELECT SUB_NO AS 과목명, STU_NO AS 학번, ENR_GRADE AS 점수
FROM ENROL;
--Q23
SELECT CONCAT(STU_DEPT, STU_NAME)
FROM STUDENT;
--Q25
SELECT *
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보';
--Q27
SELECT *
FROM STUDENT
WHERE STU_DEPT = '전기전자';
--Q29
SELECT *
FROM STUDENT
WHERE STU_WEIGHT >= 65;
--Q31
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보';
--Q33
SELECT STU_NAME
FROM STUDENT
WHERE STU_GENDER = 'M';
--Q35
SELECT *
FROM STUDENT
WHERE STU_DEPT <> '전기전자';
--Q37
SELECT STU_NO
FROM ENROL
WHERE ENR_GRADE >= 80;
--Q39
SELECT *
FROM STUDENT
WHERE STU_GRADE = 1 AND STU_DEPT = '컴퓨터정보';
--Q41
SELECT *
FROM STUDENT
WHERE STU_GENDER = 'F' AND STU_WEIGHT <= 60;
--Q43
SELECT *
FROM SUBJECT
WHERE SUB_DEPT <> '기계';
--Q45
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_HEIGHT BETWEEN 160 AND 170;
--Q47
SELECT *
FROM STUDENT
WHERE STU_GRADE = 1 OR STU_GRADE = 3;
--Q49
SELECT *
FROM STUDENT
WHERE STU_NO LIKE '____20%';
--Q51
SELECT STU_NAME
FROM STUDENT
WHERE STU_NAME LIKE '%옥%';
--Q53
SELECT STU_NO, STU_NAME
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL;
--Q55
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_GENDER = 'M' OR STU_GRADE = 1;
--Q57
SELECT STU_NO, STU_NAME
FROM STUDENT
ORDER BY STU_NAME;
--Q59
SELECT *
FROM STUDENT
ORDER BY STU_GRADE DESC;
--Q61
SELECT STU_NO, STU_NAME
FROM STUDENT
ORDER BY STU_DEPT, STU_GENDER, STU_GRADE;
--Q63
SELECT UPPER(STU_GENDER)
FROM STUDENT;
--Q65
SELECT STU_DEPT ||'과 '|| STU_GRADE ||'학년 ' || STU_NAME ||'입니다'
FROM STUDENT;
--Q67
SELECT STU_NAME, STU_DEPT, SUBSTR(STU_DEPT, 2, 1)
FROM STUDENT;
--Q69
SELECT STU_DEPT, LENGTH(STU_DEPT)
FROM STUDENT;
--Q71
SELECT INSTR(STU_DEPT, '기', 1, 1)
FROM STUDENT;
--Q73
SELECT LPAD(STU_DEPT, 20, '%')
FROM STUDENT;
--Q75
SELECT STU_NO, STU_NAME, TRUNC(STU_HEIGHT, 2)
FROM STUDENT;
--Q77
SELECT NVL(TO_CHAR(STU_HEIGHT), '미기록')
FROM STUDENT;
--Q79
SELECT STU_NO, STU_NAME, NVL(STU_HEIGHT, 0) - STU_WEIGHT
FROM STUDENT;
--Q81
SELECT NVL(NULLIF(STU_GENDER, 'F'), NULL)
FROM STUDENT;
--Q83
SELECT STU_NO, STU_NAME, STU_GENDER, STU_WEIGHT,
CASE STU_GENDER WHEN 'F' THEN STU_WEIGHT-5
                WHEN 'M' THEN STU_WEIGHT+5
                ELSE STU_WEIGHT
                END AS 변경된몸무게
                FROM STUDENT;
--Q85
SELECT MAX(STU_HEIGHT)
FROM STUDENT;
--Q87
SELECT MIN(STU_WEIGHT)
FROM STUDENT;
--Q89
SELECT MAX(STU_HEIGHT), MIN(STU_HEIGHT), MAX(STU_WEIGHT), MIN(STU_WEIGHT)
FROM STUDENT;
--Q91
SELECT COUNT(DISTINCT STU_DEPT)
FROM STUDENT;
--Q93
SELECT COUNT(*)
FROM STUDENT;
--Q95
SELECT COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT;
--Q97
SELECT COUNT(*)
FROM STUDENT
GROUP BY STU_GRADE;
--Q99
SELECT COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY COUNT(*) DESC;
--Q101
SELECT TO_CHAR(AVG(STU_HEIGHT), '999.9')
FROM STUDENT
WHERE STU_HEIGHT IS NOT NULL
GROUP BY STU_DEPT, STU_GRADE
ORDER BY AVG(STU_HEIGHT) DESC;
--Q103
SELECT MAX(STU_NO), MIN(STU_NO)
FROM STUDENT
GROUP BY STU_DEPT, STU_GRADE;
--Q105
SELECT TO_CHAR(AVG(STU_HEIGHT), '999.9')
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY AVG(STU_HEIGHT);
--Q107
SELECT TO_CHAR(AVG(STU_HEIGHT), '999.9')
FROM STUDENT
GROUP BY STU_DEPT
ORDER BY AVG(STU_HEIGHT) DESC;